version: '3.7'
services:
  populardownloads:
    image: ${registry}/jfrog-test/populardownloads:latest
    build: .
    ports:
      - '8081:8080'
    environment:
      - REDIS_URL=redis-spd:6379
    networks:
      - redis-net
    depends_on:
      - redis-spd

  redis-spd:
    container_name: redis-spd
    image: redis:4.0.14-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis-spd
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
